name = "SymmetricTensors"
uuid = "1ab33d94-6c6c-50cc-93f0-e3f623a46aa0"
authors = ["Krzysztof Domino <kdomino@iitis.pl>", "≈Åukasz Pawela <lpawela@iitis.pl>", "Piotr Gawron <gawron@iitis.pl>"]
version = "1.0.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.0, 1.1, 1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
